name: Build and Release NeoVIM Deb Files
on:
  push:
    branches:
      - main
    schedule:
    - cron: '0 0 2 * *'
  workflow_dispatch:
    inputs:
      tags:
        description: 'run'
        required: false 
        type: boolean

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Neovim Build Dependencies
        run: |
          mkdir /debs && sudo apt update -y && sudo apt upgrade -y
          sudo apt install -y ninja-build gettext cmake unzip curl git file
          git clone --depth=1 https://github.com/neovim/neovim

      - name: Build Neovim for amd64
        run: |
          cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo
          cd build && cpack -G DEB
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: neovim/build/nvim-linux64.deb
          name: nvim-linux64.deb
